%%% This file was automatically generated by snmpc_mib_to_hrl version 5.6
%%% Date: 12-May-2020::22:55:29
-ifndef('SNMP-USM-AES-MIB').
-define('SNMP-USM-AES-MIB', true).

%% Oids

-define(usmAesCfb128Protocol, [1,3,6,1,6,3,10,1,2,4]).

-define(snmpUsmAesMIB, [1,3,6,1,6,3,20]).


%% Range values


%% Default values

-endif.
